# Generated by Django 3.2.8 on 2021-11-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogfeed', '0003_alter_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
