# Generated by Django 3.2.8 on 2021-11-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogfeed', '0012_auto_20211129_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='meta_obj',
            new_name='user',
        ),
    ]
